spring:
  datasource:
    url: jdbc:postgresql://192.168.1.25:5432/home-test
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: smart_home
jwt:
  secret: tLPwE!Tqo263nH1vGqhJCztiC5VH@HxKoaqq86GoSUWeelyUSqP@9AQUvoTbZ!2yj^xQU@ic$N$ljNIGVifgzUxy5OGqdPkfltuMj%o$W@nNajRa%osN7VexIMKl8S7H
  expiration: 86400000