spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smart-home
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: smart_home

jwt:
  secret: wwwwQJIKGS78nt7686NSF7nfs76NFS7689w.i,e21;+E'!EQ'ew
  expiration: 86400000